SECRET_KEY = '10726629'
DEBUG = True
MONGODB_DB = 'printservice'
HOSTNAME = 'http://127.0.0.1:5000'
UPLOAD_FOLDER_IMG = '/Users/Pongsaton/Desktop/PrintService Project/printservice/static/images'
UPLOAD_FOLDER_FILES = '/Users/Pongsaton/Desktop/PrintService Project/printservice/static/upload_files'
STATIC_IMAGE_URL = 'images'
STATIC_FILE_URL = 'upload_files'
# AWS_BUCKET = 'PrintService'
# AWS_CONTENT_URL = 'https://s3-us-west-2.amazonaws.com'
AWS_BUCKET = False
AWS_CONTENT_URL = ''
AWS_SEND_MAIL = True
